name: Pre-release

on:
  release:
    types: [prereleased]

jobs:

  polite-module:

    name: Polite Module
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: christianwong/${{ secrets.REPO_POLITE }}
          ref: main
          token: ${{ secrets.TOKEN }}
      - name: Create Release
        run: |
          gh release create --prerelease ${{ github.event.release.tag_name }} --notes "${{ github.event.release.body }}" --title "${{ github.event.release.name }} by ${{ github.event.release.author.login }}"


  alfredus-module:

    name: Alfredus Module
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: christianwong/${{ secrets.REPO_ALFREDUS }}
          ref: main
          token: ${{ secrets.TOKEN }}
      - name: Create Release
        run: |
          gh release create --prerelease ${{ github.event.release.tag_name }} --notes "${{ github.event.release.body }}" --title "${{ github.event.release.name }} by ${{ github.event.release.author.login }}"


  delivery-module:

    name: Delivery Module
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: christianwong/${{ secrets.REPO_DELIVERY }}
          ref: main
          token: ${{ secrets.TOKEN }}
      - name: Create Release
        run: |
          gh release create --prerelease ${{ github.event.release.tag_name }} --notes "${{ github.event.release.body }}" --title "${{ github.event.release.name }} by ${{ github.event.release.author.login }}"

