name: Release

on:
  release:
    types: [released]
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  deploy-release:

    name: Deploy Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: christianwong/${{ secrets.SAMPLE_REPO }}
          ref: main

      - name: Create Release on SAMPLE_REPO
        run: |
          gh release create -p ${{ github.event.release.tag_name }} --notes "Created from GitHub Actions."
