name: Release

on:
  release:
    types: [released]
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:

  polite-module:

    name: Polite Module
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: christianwong/${{ secrets.REPO_POLITE }}
          ref: main
          token: ${{ secrets.TOKEN }}
      - name: Create Release
        run: |
          gh release create ${{ github.event.release.tag_name }} --notes "Created from GitHub Actions." --title "New Release"


  alfredus-module:

    name: Alfredus Module
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: christianwong/${{ secrets.REPO_ALFREDUS }}
          ref: main
          token: ${{ secrets.TOKEN }}
      - name: Create Release
        run: |
          gh release create ${{ github.event.release.tag_name }} --notes "Created from GitHub Actions." --title "New Release"


  delivery-module:

    name: Delivery Module
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: christianwong/${{ secrets.REPO_DELIVERY }}
          ref: main
          token: ${{ secrets.TOKEN }}
      - name: Create Release
        run: |
          gh release create ${{ github.event.release.tag_name }} --notes "Created from GitHub Actions." --title "New Release"

