name: Release

on:
  release:
    types: [released]
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  deploy-release:

    name: Deploy Release
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: christianwong/${{ secrets.SAMPLE_REPO }}
          ref: main
          token: ${{ secrets.TOKEN }}

      - name: Create Release on SAMPLE_REPO
        run: |
          ls
          cd ${{ secrets.SAMPLE_REPO }}
          gh release create v0.1
